language: cpp
arch:
  - amd64
  - ppc64le
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libgtest-dev libopenmpi-dev libsparsehash-dev
  - |
    if [[ "$TRAVIS_CPU_ARCH" = "ppc64le" ]]; then
     sudo apt-get install g++-4.8
    fi
script:
  - ./autogen.sh
  - ./configure --with-mpi=/usr/lib/openmpi
  - make
  - make check
